<?php
	/**
	 * Export to PHP Array plugin for PHPMyAdmin
	 * @version 4.8.3
	 */

	/**
	 * Database `apollo29_erp`
	 */

	/* `apollo29_erp`.`branches` */
	$branches = array(
		array('code' => '1326','nome' => 'Handyman Xentro Mall Vigan','address' => '2nd Floor Xentro Mall, Salcedo Street corner Del Pilar Street, Vigan, Ilocos Sur','storecode' => '391'),
		array('code' => '1347','nome' => 'Handyman Xentro Mall Tanay','address' => 'Ground Floor, Xentro Tanay Town Center, Tanay Rizal','storecode' => '418'),
		array('code' => '1260','nome' => 'Handyman Xentro Mall Roxas Isabela','address' => 'ground floor xentromall,don mariano marcos avenue roxas isabela.','storecode' => '368'),
		array('code' => '1334','nome' => 'Handyman Xentro Mall Batangas','address' => 'Batangas','storecode' => '410'),
		array('code' => '1332','nome' => 'Handyman Xentro Mall Antipolo','address' => 'Mambugan Antipolo City','storecode' => '403'),
		array('code' => '1018','nome' => 'Handyman Wm Violago','address' => '#222 Violago Compound E. Rodriguez Ave., Q.C.','storecode' => '202'),
		array('code' => '1208','nome' => 'Handyman Wm Trece Martires','address' => 'Governor','storecode' => '324'),
		array('code' => '1152','nome' => 'Handyman Wm Tanauan','address' => 'Handyman Walter mart Tanauan Lipa batangas','storecode' => '259'),
		array('code' => '1256','nome' => 'Handyman Wm Tagaytay','address' => 'Upper ground flr. Waltermart, Nasugbo Road, Brgy. Silang Crossing, Tagaytay City, Cavite','storecode' => '375'),
		array('code' => '1035','nome' => 'Handyman Wm Sucat','address' => ' 2nd floor, WalterMart Community Mall, Sucat Parañaque','storecode' => '309'),
		array('code' => '1066','nome' => 'Handyman Wm Sta. Rosa','address' => 'level 2 walter mart sta.rosa laguna','storecode' => '252'),
		array('code' => '1052','nome' => 'Handyman Wm Sta. Maria','address' => '2nd flr.waltermart center, sta.maria provincial road cor.by pass road brgy.sta.clara, sta.maria bulacan','storecode' => '258'),
		array('code' => '1354','nome' => 'Handyman wm San Jose Nueva Ecija','address' => '2nd Floor Walter Walter San Jose Nueva Ecija','storecode' => '427'),
		array('code' => '1048','nome' => 'Handyman Wm San Fernando','address' => '1st Level Waltermart Building Barangay San Agustin, City of San Fernando','storecode' => '300'),
		array('code' => '1173','nome' => 'Handyman WM Plaridel','address' => '2nd Flr.Waltermart Shopping Center Banga 1st Plaridel bulacan','storecode' => '256'),
		array('code' => '1019','nome' => 'Handyman Wm North Edsa','address' => 'Waltermart Center North Edsa Dangay St. Veterans Village, Quezon City','storecode' => '204'),
		array('code' => '1068','nome' => 'Handyman Wm Makiling','address' => 'G/F Waltermart Center Brgy. Makiling National Highway, Calamba City, laguna
','storecode' => '310'),
		array('code' => '1027','nome' => 'Handyman Wm Makati','address' => '4 th floor.whi mall 790 chino roces corner a. arnaiz ave.makati city','storecode' => '203'),
		array('code' => '1062','nome' => 'Handyman Wm Lipa','address' => 'Expansion Bldg. Robinson Mall, Brgy. Mataas na Lupa, Lipa City Batangas','storecode' => '158'),
		array('code' => '1160','nome' => 'Handyman Wm Guguinto Bulacan','address' => 'ground floor, Waltermart Mall, McArthur Hiway, Guiguinto, Bulacan','storecode' => '322'),
		array('code' => '1172','nome' => 'Handyman WM Gen. Trias','address' => 'Waltermart General Trias, Governors Drive, Barrio Mangahan, General Trias, 4107, Cavite','storecode' => '255'),
		array('code' => '1207','nome' => 'Handyman Wm Gapan','address' => '2 ND FLR.WM GAPAN REAL ST NUEVA ECIJA','storecode' => '257'),
		array('code' => '1074','nome' => 'Handyman Wm Dasmarinas','address' => 'Emilio Aguinaldo Hwy, Dasmari?as','storecode' => '251'),
		array('code' => '1075','nome' => 'Handyman Wm Carmona','address' => 'Handyman  Walter mart Carmona Cavite City','storecode' => '254'),
		array('code' => '1067','nome' => 'Handyman Wm Calamba','address' => '2nd Floor WHI Super Center, Brgy. Real St., Calamba Laguna
','storecode' => '253'),
		array('code' => '1175','nome' => 'Handyman Wm Bicutan','address' => '2nd floor waltermart bicutan  east service road bicutan taguig city','storecode' => '339'),
		array('code' => '1284','nome' => 'Handyman Welcome Mercedes','address' => '2nd level Wellcome Mercedes, Mercedes Avenue corner Market Avenue Brgy. San Miguel, Pasig City','storecode' => '379'),
		array('code' => '1362','nome' => 'Handyman Villamonte East','address' => '2nd Floor, East 3 Commercial Center, Helvetia Heights Subd., Burgos Extension, Brgy. Villamonte, Bacolod City','storecode' => '421'),
		array('code' => '1017','nome' => 'Handyman Victoria Tower Timog','address' => 'Victoria Tower Ground Floor Timog Avenue, Quezon City','storecode' => '122'),
		array('code' => '1154','nome' => 'Handyman Victoria Balanga Bataan','address' => '3rd flr.Victoria Mall P.Paterno st.Balanga Bataan','storecode' => '303'),
		array('code' => '1294','nome' => 'Handyman Umbria','address' => 'Level 2, Umbria Mall, National Highway, Tulay Bato, Brgy. San Antonio, Binan Laguna 4024 Philippines','storecode' => '365'),
		array('code' => '1013','nome' => 'Handyman Trinoma Mall','address' => '2nd Floor Space#2083 North Depot Commercial Center Barangay Pag-asa, Quezon City','storecode' => '117'),
		array('code' => '1278','nome' => 'Handyman Townville Regalado','address' => 'Regalado avenue, Fairview, Quezon City','storecode' => '367'),
		array('code' => '1010','nome' => 'Handyman Tandang Sora','address' => 'RMR Square Mall, Brgy. Pasong Tamo, Philand Drive,Tandang Sora, Quezon City','storecode' => '311'),
		array('code' => '1002','nome' => 'Handyman Talavera Isabela','address' => '2 nd floor talavera square mall maharlika rd.calamagui ilagan city isabela','storecode' => '305'),
		array('code' => '1025','nome' => 'Handyman Starmall Shaw','address' => 'edsa cor.shaw blvd.mandaluyong city.','storecode' => '107'),
		array('code' => '1034','nome' => 'Handyman Starmall Alabang','address' => 'Ground Floor Metropolis Alabang, Muntinlupa City','storecode' => '104'),
		array('code' => '1080','nome' => 'Handyman Sta.lucia','address' => 'marcos h-way corner felix ave. cainta rizal','storecode' => 'STA1'),
		array('code' => '1186','nome' => 'Handyman Square Malabon','address' => 'Handyman Citi Square Malabon (C4 Road Dagat Dagatan Malabon) store code #112','storecode' => '112'),
		array('code' => '1187','nome' => 'Handyman Square Banaue','address' => '3rd. Floor Z.Square Mall Delmonte Ave. Corner Banawe st.Quezon city','storecode' => '327'),
		array('code' => '1225','nome' => 'Handyman Spark Place Mall','address' => 'Spark Place Mall 2nd floor P. Tuazon corner 10th ave araneta center cubao (sc. 347)','storecode' => '347'),
		array('code' => '1293','nome' => 'Handyman Southpark','address' => 'Ground Floor Southpark Ayala Mall Alabang, Muntinlupa','storecode' => '388'),
		array('code' => '1237','nome' => 'Handyman South Town Center','address' => '2nd Floor, South Town Center, Cebu Road Tabunok Talisay City, Cebu','storecode' => '363'),
		array('code' => '1171','nome' => 'Handyman Silang','address' => 'Premier Plaza, Emilio Aguinaldo H-Way, Brgy. Lucsuhin Silang, Cavite','storecode' => '325'),
		array('code' => '1379','nome' => 'Handyman Shopwise San Fernando Pampanga','address' => '1st Level, Barangay Maimpis, Mc Arthur Hiway, City Of San Fernando Pampanga','storecode' => ''),
		array('code' => '1310','nome' => 'Handyman Shaw Center Mall','address' => '3rd flr.shaw centermall,shaw bldv.cor nueve de pebrero mandaluyong city','storecode' => '404'),
		array('code' => '1216','nome' => 'Handyman Santiago','address' => 'Santiago City Philippines','storecode' => '334'),
		array('code' => '1258','nome' => 'Handyman San Francisco Agusan','address' => 'Pan-Philippine Hwy, Barangay 5, San Francisco, Agusan del Sur
','storecode' => '374'),
		array('code' => '1317','nome' => 'Handyman San Carlos','address' => 'San Carlos Pangasinan','storecode' => '407'),
		array('code' => '1364','nome' => 'Handyman RP Valencia','address' => 'RP Valencia, Sayre Highway, Valencia City, Bukidnon','storecode' => '422'),
		array('code' => '1342','nome' => 'Handyman Rp Tuguegarao','address' => '2nd floor Robinsons place,Tuguegarao brgy.tanza,Tuguegarao cagayan','storecode' => '395'),
		array('code' => '1275','nome' => 'Handyman Rp Tagum','address' => '2nd level- Robinsons Place Tagum National Highway Barangay Magugpo Tagum City, Davao del Norte','storecode' => '376'),
		array('code' => '1178','nome' => 'Handyman Rp Tagaytay','address' => 'Brgy Maharlika Summit rigde, Prominade Tagaytay City','storecode' => '164'),
		array('code' => '1144','nome' => 'Handyman Rp Tacloban','address' => '2nd Floor Robinsons Place Tacloban Tabuan National Hwy Fatima Village, Tacloban City','storecode' => '192'),
		array('code' => '1065','nome' => 'Handyman Rp Sta. Rosa','address' => 'level 1 robinson place sta.rosa brgy.tagapo sta.rosa city','storecode' => '156'),
		array('code' => '1193','nome' => 'Handyman Rp Roxas','address' => '2nd level Robinson','storecode' => '337'),
		array('code' => '1047','nome' => 'Handyman Rp Pulilan','address' => 'Dona Remedios Trinidad Highway,Pulilan Junction Barangay Cut-cot Pulilan Bulacan','storecode' => '165'),
		array('code' => '1026','nome' => 'Handyman Rp Pioneer','address' => 'rhi place pioneer,edsa cor,pioneer st.mandaluyong city','storecode' => '116'),
		array('code' => '1341','nome' => 'Handyman Rp Pavia','address' => '2nd Level, Robinson Place Vice President Fernando Avenue, Pavia, Iloilo','storecode' => '419'),
		array('code' => '1051','nome' => 'Handyman Rp Pampanga','address' => 'Level 1 Gapan Olongapo Rd. Brgy. San Jose, San Fernando Pampanga','storecode' => '110'),
		array('code' => '1153','nome' => 'Handyman Rp Palawan','address' => '2nd level, Robinsons Place, National Highway, Brgy. San Manuel, Puerto Princesa City, Palawan','storecode' => '308'),
		array('code' => '1023','nome' => 'Handyman Rp Otis','address' => '2 nd floor.robinsons place manila paz guanzon st.pac','storecode' => '119'),
		array('code' => '1335','nome' => 'Handyman RP Ormoc','address' => '2nd Level RP Ormoc Palo Carigara OrmocCity Road Brgy. Cogon , Ormoc City, Leyte','storecode' => '397'),
		array('code' => '1155','nome' => 'Handyman Rp Novaliches','address' => 'Grd.flr.Robinsons Place Novaliches,Quirino Highway Nova.Q.C','storecode' => '109'),
		array('code' => '1325','nome' => 'Handyman RP North Tacloban','address' => '2nd level Robinson Place North Tacloban, Brgy. Abucay, Tacloban City','storecode' => '411'),
		array('code' => '1312','nome' => 'Handyman RP Naga','address' => '2nd. Level Robinsons Place , Roxas Ave. cor. Almeda Hi - way Brgy. Triangulo , Naga City','storecode' => '383'),
		array('code' => '1031','nome' => 'Handyman Rp Metroeast','address' => '3 rd level rhi place metroeast marcos high way cor.imelda ave pasig city','storecode' => '111'),
		array('code' => '1192','nome' => 'Handyman Rp Malolos','address' => '3rd flr Robinson\'s Place,Mc.Arthur Highway,Brgy.Malolos,Malolos Bulacan','storecode' => '333'),
		array('code' => '1198','nome' => 'Handyman Rp Malabon','address' => '2nd floor Robinsons Town Mall Malabon, Lot 1, 2, 3 -A7 ; 7-11 & 12 Block 1 #5  Governor St., Malabon City ','storecode' => '332'),
		array('code' => '1069','nome' => 'Handyman Rp Los Banos','address' => 'RHI Town Mall Lopez Avenue Batong Malake, Los Banos, Laguna','storecode' => '154'),
		array('code' => '1061','nome' => 'Handyman Rp Lipa','address' => 'Brgy.Mataas na Lupa,Lipa City','storecode' => '158'),
		array('code' => '1240','nome' => 'Handyman RP Las Pinas','address' => '345 alabang zapote road brgy talon laspinas city','storecode' => '349'),
		array('code' => '1042','nome' => 'Handyman Rp Laoag','address' => 'Barangay 1 san francisco ,San Nicolas ilocos norte','storecode' => '169'),
		array('code' => '1287','nome' => 'Handyman Rp Jaro','address' => '2nd Level, Robinsons Place, E. Lopez St., Brgy. San Vicente, Jaro, Iloilo City','storecode' => '384'),
		array('code' => '1183','nome' => 'Handyman Rp Imus','address' => 'Ground Floor Robinsons Place Imus, Cavite Philippines','storecode' => '151'),
		array('code' => '1095','nome' => 'Handyman Rp Iloilo','address' => '2nd level Robinson Place, Ledesma st. Iloilo City','storecode' => '187'),
		array('code' => '1305','nome' => 'Handyman RP ILigan ','address' => '2nd level- Robinsons Place Iligan, Macapagal Avenue, Iligan City','storecode' => '385'),
		array('code' => '1140','nome' => 'Handyman Rp Gensan','address' => 'J.Catolico St. General Santos City','storecode' => '194'),
		array('code' => '1280','nome' => 'Handyman Rp General Trias','address' => '2nd Floor Robinsons Place General Trias Cavite','storecode' => '382'),
		array('code' => '1022','nome' => 'Handyman Rp Galleria','address' => 'Robinsons Handyman Inc. Food Boulevard Robinsons Galleria Edsa Corner Ortigas Avenue Pasig City ','storecode' => '101'),
		array('code' => '1024','nome' => 'Handyman Rp Ermita','address' => '3 rd level robinsons place m.adriatico st.malate manila.','storecode' => '103'),
		array('code' => '1100','nome' => 'Handyman Rp Dumaguete','address' => '2nd level robinsons place dumguete central business district calindagan cor. south rd.dumaguete city','storecode' => '195'),
		array('code' => '1139','nome' => 'Handyman Rp Davao','address' => 'J.P. Laurel Ave. Bajada, Davao City','storecode' => '193'),
		array('code' => '1150','nome' => 'Handyman Rp Dasmarinas','address' => 'Aguinaldo Hi-way, Brgy. Pala-pala, Dasmari?as, Cavite','storecode' => '157'),
		array('code' => '1376','nome' => 'Handyman Rp Cotabato','address' => 'Ground floor, Mall of Ainor, Sinsuat Avenue, Rosary Heights 9, Cotabato','storecode' => ''),
		array('code' => '1108','nome' => 'Handyman Rp Cebu','address' => 'Robinsons Place, Fuente Osmena Cor. Janes Avenue, Cebu City','storecode' => '182'),
		array('code' => '1044','nome' => 'Handyman Rp Calasiao','address' => 'Calasiao,National Hi-way, Barangay San Miguel, Calasiao, Pangasinan ','storecode' => '307'),
		array('code' => '1078','nome' => 'Handyman Rp Cainta','address' => '2nd level rhi supermarket center caintz a.junction ortigas ave. ext.','storecode' => '114'),
		array('code' => '1176','nome' => 'Handyman Rp Cagayan De Oro 2','address' => 'Lim Kitkai Mall Cagaya','storecode' => '335'),
		array('code' => '1138','nome' => 'Handyman Rp Cagayan De Oro','address' => 'Lim Kitkai Mall Cagayan De Oro City','storecode' => '183'),
		array('code' => '1149','nome' => 'Handyman Rp Cabanatuan','address' => 'PACIFIC MALL. BRGY, CONCEPTION KM111-MAHARLIKA HIGH WAY CABANATUAN, NUEVA ECIJA ','storecode' => '166'),
		array('code' => '1191','nome' => 'Handyman Rp Butuan','address' => '2nd Level Robinsons Place, Km J.C Aquino St. Butuan City. ','storecode' => '338'),
		array('code' => '1177','nome' => 'Handyman Rp Bacolod','address' => '2nd level Robinson Place, Mandalagan St.Bacolod City','storecode' => '181'),
		array('code' => '1262','nome' => 'Handyman Rp Antique','address' => 'Handyman Antique 2nd Level, Robinson Place Ilo-ilo Antique Road Brgy. San Jose Buenavista, Antique Panay','storecode' => '373'),
		array('code' => '1228','nome' => 'Handyman RP Antipolo','address' => '2nd flr robinsons place antipolo sumulung hiway cicumference ave. brgy. dela paz Antipolo city','storecode' => '348'),
		array('code' => '1049','nome' => 'Handyman Rp Angeles','address' => '3rd Floor Robinson','storecode' => '160'),
		array('code' => '1020','nome' => 'Handyman Riverbanks Marikina','address' => '84 A Bonifacio Ave.Barangka, Marikina City ','storecode' => '108'),
		array('code' => '1005','nome' => 'Handyman Puregold Caloocan','address' => '2nd Floor Puregold Caloocan, Samson Road, Monumento, Caloocan City','storecode' => '120'),
		array('code' => '1298','nome' => 'Handyman Paso De Blas','address' => '3rd Level Puregold Paso De Blas Mall, Paso De Blas Road Corner east service road General Luis St. Brgy Paso De Blas','storecode' => '390'),
		array('code' => '1158','nome' => 'Handyman Parkmall Cebu','address' => 'Ground Floor North 2 ,Parkmall Quiano Avenue,Cebu City ','storecode' => '198'),
		array('code' => '1194','nome' => 'Handyman Pagsanjan','address' => 'Ground floor of CLA Town centermall, National Highway, Samban, Brgy Binan Pagsanjan Laguna','storecode' => '342'),
		array('code' => '1081','nome' => 'Handyman Pacific Mall Lucena','address' => 'Handyman Pacific mall Lucena. Lucena City','storecode' => '159'),
		array('code' => '1311','nome' => 'Handyman Ozamiz','address' => '3rd floor, Geege Mall Burgos st. corner Pingol st. Ozamiz City.','storecode' => '405'),
		array('code' => '1291','nome' => 'Handyman One Mall Valenzuela','address' => '2nd level, 6008 Gen T. De Leon Road Brgy. Gen. T. De Leon Valenzuela City','storecode' => '389'),
		array('code' => '1151','nome' => 'Handyman Nuciti Batangas','address' => 'Bry.concepion batangas city','storecode' => '321'),
		array('code' => '1163','nome' => 'Handyman Nepomall Dagupan','address' => 'Nepo Mall Dagupan G/F Nepomall Bldg., Arellano St. Dagupan City,Pangasinan','storecode' => '161'),
		array('code' => '1050','nome' => 'Handyman Nepomall Angeles','address' => '3rd Floor Nepomall Teresa Avenue Corner St.Joseph Street, Angeles City, Pampanga','storecode' => '163'),
		array('code' => '1313','nome' => 'Handyman NE Mall Baler','address' => 'Handyman NE Mall Baler, Aurora','storecode' => '406'),
		array('code' => '1165','nome' => 'Handyman Montalban2 Towncenter','address' => 'ground floor e. rodriquez brgy. san jose montalban rizal','storecode' => '125'),
		array('code' => '1079','nome' => 'Handyman Montalban Towncenter','address' => 'ground floor e. rodriquez brgy. san jose montalban rizal','storecode' => '124'),
		array('code' => '1236','nome' => 'Handyman Metrotown Mall','address' => '2nd Flr.Metrotown Mall cor.Juan Luna St.Sto.Cristo Tarlac City','storecode' => '360'),
		array('code' => '1096','nome' => 'Handyman Marymart Iloilo','address' => '2nd Flr Marymart Mall, Valeria St. Iloilo City ','storecode' => '184'),
		array('code' => '1206','nome' => 'Handyman Mart One Dumaguete','address' => 'Perdices st. Dumaguete citu','storecode' => '329'),
		array('code' => '1057','nome' => 'Handyman Magic Star Mall Tarlac','address' => 'Magic Star Mall Romulo Boulevard,Tarlac City','storecode' => '155'),
		array('code' => '1162','nome' => 'Handyman Lucky Gold Pasig','address' => '2nd floor, Lucky Gold Plaza, Ortigas Avenue Extention, Pasig city','storecode' => '323'),
		array('code' => '1168','nome' => 'Handyman Lucky China Town 2','address' => 'citi place commercial ctr.unit lct3-2b calje felipe.cornerlachambre st.brgy.293 zone 28. binondo manila','storecode' => '401'),
		array('code' => '1283','nome' => 'Handyman Liloan','address' => 'Lower Ground Floor,Gaaisano Grand Mall, Brgy Poblacion,Liloan,Cebu','storecode' => '380'),
		array('code' => '1220','nome' => 'Handyman Lemery','address' => 'Bry.malinis lemery batangas','storecode' => '343'),
		array('code' => '1083','nome' => 'Handyman Lcc Naga','address' => 'LCC Central Mall Naga Business Park Felix Plazo St.,Naga City','storecode' => '352'),
		array('code' => '1086','nome' => 'Handyman Lcc Legazpi','address' => 'Ground Flr. Expressmart Bldg.,Peñaranda St.,Legaspi City','storecode' => '351'),
		array('code' => '1303','nome' => 'Handyman Lancaster','address' => '2nd Floor North Courtyard Retail Building Suntech Park, Lancaster New City, Imus, Cavite','storecode' => '392'),
		array('code' => '1184','nome' => 'Handyman Lamuan Marikina','address' => 'graceland plaza,lamuan marikina','storecode' => '313'),
		array('code' => '1224','nome' => 'Handyman Il Centromall','address' => 'marcos h-way corner felix ave. cainta rizal','storecode' => '355'),
		array('code' => '1239','nome' => 'Handyman Iba Zambales','address' => '2nd floor iba town center national road zone 1 poblacion iba zambales','storecode' => '357'),
		array('code' => '1322','nome' => 'Handyman Holiday Island Caloocan','address' => '-2nd flr.Holiday Island Dutong st.corner Kanlaon st.Bagong Silang Caloocan City.','storecode' => '414'),
		array('code' => '1161','nome' => 'Handyman Harbor Point Subic','address' => '2nd level of Harbor Point, Rizal Avenue, Subic Bay Freeport Zone, Subic, Zambales ','storecode' => '317'),
		array('code' => '1167','nome' => 'HANDYMAN GT MOLO','address' => '2ndï¿½floor, GT Mall Plaza, M.H. Del Pilar Street, Molo, Iloilo Cityï¿½','storecode' => '326'),
		array('code' => '1164','nome' => 'Handyman Gt Ilo-ilo','address' => 'Ledesma St. Iloilo City','storecode' => '326'),
		array('code' => '1290','nome' => 'Handyman Gregorian','address' => 'Gregorian, Rizal St., Rosario St., Serrano St, Old albay Disctrict, Legazpi City','storecode' => '341'),
		array('code' => '1190','nome' => 'Handyman Gmall Toril','address' => 'Gaisano Mall of Toril, Lim Street, Toril, Davao City, Davao Region, Philippines','storecode' => '346'),
		array('code' => '1137','nome' => 'Handyman Gaisano Tagum','address' => 'L/G Gmall of Tagum, National Highway Briz Dist. Magugpo East, Tagum City, Davao del Norte.','storecode' => '199'),
		array('code' => '1094','nome' => 'Handyman Gaisano Roxas','address' => '2nd Level Gaisano Mall, Arnaldo Blvd., Roxas City ','storecode' => '186'),
		array('code' => '1136','nome' => 'Handyman Gaisano Panabo','address' => 'G/F Gaisano Grand Panabo, Quezon St. Sto. Nino Panabo City, Davao del Norte.','storecode' => '196'),
		array('code' => '1238','nome' => 'Handyman Gaisano Mactan Island Mall 2','address' => 'Ground Floor Island Mactan Mall 2, M.L Quezon, National Highway Pusok Lapu-Lapu City, Cebu
','storecode' => '354'),
		array('code' => '1110','nome' => 'Handyman Gaisano Mactan','address' => '1st level Gaisano Mall Mactan, Basak Cor.Agas Rd.Lapu-Lapu City','storecode' => '197'),
		array('code' => '1093','nome' => 'Handyman Gaisano Kalibo','address' => 'UGF, Gaisano Mall Kalibo Aklan ','storecode' => '302'),
		array('code' => '1339','nome' => 'Handyman Gaisano Iriga','address' => 'Gaisano Capital Iriga City','storecode' => '413'),
		array('code' => '1368','nome' => 'Handyman Gaisano Grand Northgate Mandaue','address' => '2nd Level , Gaisano Grand Mandaue NorthGate MallNational Highway, Brgy. Basak, Mandaue City, Cebu','storecode' => '429'),
		array('code' => '1350','nome' => 'Handyman Gaisano Grand Mall Silay','address' => 'Ground Floor, Gaisano Grand Mall, National Road, Silay City, Negros occidental','storecode' => '412'),
		array('code' => '1328','nome' => 'Handyman Gaisano Grand Calbayog','address' => '2nd Floor Gaisano Mall Navarro Street. Brgy. Central Poblacion Calbayog City Samar','storecode' => '408'),
		array('code' => '1344','nome' => 'Handyman Gaisano Gensan','address' => '2nd floor Gaisano Mall Gensan, Jose Catholico Sr. Avenue, General Santos City','storecode' => '416'),
		array('code' => '1271','nome' => 'Handyman Gaisano Digos','address' => '2nd floor Gaisano Digos Mall, National High Way Digos City, Davao Del Sur','storecode' => '378'),
		array('code' => '1135','nome' => 'Handyman Gaisano Davao','address' => 'J.P. Laurel Ave, Obrero, Davao City, 8000 Davao del Sur
','storecode' => '185'),
		array('code' => '1343','nome' => 'Handyman Gaisano Binangonan','address' => '2nd floor Gaisano Capital Binangonan, Manila East Road, Brgy. Calumpang Binangonan','storecode' => '409'),
		array('code' => '1033','nome' => 'Handyman Festival Mall Alabang','address' => 'Anchor B Festival Mall, Filinvest Alabang, Muntinlupa City','storecode' => '115'),
		array('code' => '1073','nome' => 'Handyman Federal Gen Trias','address' => 'Oriental Garden Governors Drive Brgy. Manggahan General Trias, Cavite','storecode' => '306'),
		array('code' => '1188','nome' => 'Handyman Farmers Cubao','address' => '(New Farmers Plaza, Araneta Center, Q.C) Store code #106','storecode' => '106'),
		array('code' => '1006','nome' => 'Handyman Fairview Centermall','address' => 'Lower Ground, Fairview Mall Center Commonwealth Ave. Cor. Regalado Ave. Fairview, Quezon City','storecode' => '105'),
		array('code' => '1085','nome' => 'Handyman Emall Naga','address' => 'E-mall Penafrancia Avenue Corner P. Diaz E. Angeles St. Naga City, Bicol','storecode' => '162'),
		array('code' => '1109','nome' => 'Handyman Emall Cebu','address' => '2nd. Floor Elizabeth Mall Corner Natalio B. Bacalso Ave Cebu City Cebu, Philippines','storecode' => '189'),
		array('code' => '1205','nome' => 'Handyman Ema Tc Meycauayan','address' => 'Ema Town Center Camalig,Meycauayan Bulacan','storecode' => '330'),
		array('code' => '1159','nome' => 'Handyman City Walk Tarlac','address' => 'Ground Floor City Walk Mall,Zamora Street, Tarlac City','storecode' => '171'),
		array('code' => '1251','nome' => 'Handyman City Mall Roxas','address' => 'City Mall Roxas','storecode' => '358'),
		array('code' => '1254','nome' => 'Handyman Cherry Foodarama','address' => '2nd flr. Cherry Foodarama, Shaw blvd., Mandaluyong City','storecode' => '361'),
		array('code' => '1064','nome' => 'Handyman Centro Pacita','address' => 'Ground Floor, Centro Pacita National Highway, San Pedro Laguna
','storecode' => '167'),
		array('code' => '1273','nome' => 'Handyman Catarman','address' => 'Catarman, Southern Leyte','storecode' => '372'),
		array('code' => '1071','nome' => 'Handyman Canlubang','address' => 'I mall canlubang ground floor','storecode' => '312'),
		array('code' => '1001','nome' => 'Handyman Calapan Mindoro','address' => '2nd Floor, Neo Calapan Mall, Brgy. Lumang Bayan, Calapan City, Oriental Mindoro','storecode' => '200'),
		array('code' => '1195','nome' => 'Handyman Cabuyao','address' => 'ground Floor of Centro mall, Arabella, Pulo Cabuyao Laguna','storecode' => '345'),
		array('code' => '1134','nome' => 'Handyman C3 Mall Pagadian','address' => 'C3 Mall, Poblacion Pagadian City','storecode' => '304'),
		array('code' => '1346','nome' => 'Handyman Buhangin Davao','address' => '2nd Level, Gaisano Grand Fiesta Mall, Buhangin-Cabantian Road, Buhangin, Davao City','storecode' => '396'),
		array('code' => '1143','nome' => 'Handyman Bohol Quality Mall','address' => 'Galleria Luisa, Gov. Gallares Street, Tagbilaran City Bohol','storecode' => '340'),
		array('code' => '1032','nome' => 'Handyman Bf Paranaque','address' => '2nd Floor Robinsons BF Ruins Aguirre Avenue, Elsie Gaches Corner G. Puyat St.Bf Homes Paranaque','storecode' => '121'),
		array('code' => '1265','nome' => 'Handyman Bay Garden Macapagal','address' => 'JW Diokno Blvd. MAll Of Asia Complex Pasay ','storecode' => '356'),
		array('code' => '1318','nome' => 'Handyman Bay City Mall Calapan','address' => 'Ground Floor, Nucuti Mall, J.P. Rizal Brgy Camilmil, Calapan City, Oriental Mindoro','storecode' => '400'),
		array('code' => '1333','nome' => 'Handyman Bay City Macapagal','address' => '4th Floor Of WMall, Macapagal Avenue, Corner Way, Pasig City','storecode' => '260'),
		array('code' => '1272','nome' => 'Handyman Banyan Nueva Ecija','address' => 'G/F Banyan Center maharlika Hi way talauna Nueva Ecija','storecode' => '364'),
		array('code' => '1046','nome' => 'Handyman Balagtas Bulacan','address' => 'Balagtas town center, MC Arthur Hi Way Borol 1st. Balagtas bulacan','storecode' => '170'),
		array('code' => '1243','nome' => 'Handyman Baguio Centerpoint ','address' => 'Baguio Centerpoint Plaza, Marcos Highway, Bakakeng Central, Baguio City','storecode' => '362'),
		array('code' => '1003','nome' => 'Handyman Baguio Centermall','address' => '3rd flr.Baguio Center Mall,Magsaysay Baguio City','storecode' => '153'),
		array('code' => '1351','nome' => 'Handyman Ayala Mall Circuit','address' => 'Level 3 Ayala Malls Circuit, Circuit Makati, Hippodromo St., Brgy. Carmona, Makati City','storecode' => '417'),
		array('code' => '1182','nome' => 'Handyman Ayala Imus','address' => 'Daang Hari Road corner Aguinaldo Highway, Brgy. Anabu II-E, Imus City','storecode' => '316'),
		array('code' => '1321','nome' => 'Handyman Ayala Feliz Pasig','address' => '4th level, Ayala Feliz, Marcos Highway, Cor. E. Rodriguez Ave, Brgy. Dela Paz, Pasig City','storecode' => '402'),
		array('code' => '1320','nome' => 'Handyman Ayala Arvo Marikina','address' => 'Ground floor Ayala Malls Marikina, Liwasang Kalayaan, Marikina Heights, Marikina City','storecode' => '399'),
		array('code' => '1281','nome' => 'Handyman Arvo Legazpi','address' => 'Third Floor Ayala Malls Legazpi, Rizal St. Corner Quezon Ave., Brgy. Capantawan Legazpi City, Albay','storecode' => '377'),
		array('code' => '1244','nome' => 'Handyman Arvo Dasmarinas','address' => 'Upper Ground Flr. Robinsons Arvo Dasmariñas Cavite, Molino Paliparan Rd. Dasmariñas','storecode' => '344'),
		array('code' => '1219','nome' => 'Handyman Alphaland','address' => 'Handyman','storecode' => ''),
		array('code' => '1016','nome' => 'Handyman Alimall Cubao','address' => 'Alimall Foodcourt, Cubao Quzon City','storecode' => '102'),
		array('code' => '1029','nome' => 'Handyman Agora San Juan','address' => 'Ground floor n. domingo cor.blumentrit st.san juan city (puregold agora )','storecode' => '118'),
		array('code' => '1246','nome' => 'Handyman Agimat Imus','address' => 'Agimat Mall, Buhay na Tubig St., cor. Emilio Aguinaldo Highway, Imus, Cavite','storecode' => '350'),
		array('code' => '1133','nome' => 'Handyman Abreeza Davao','address' => '3rd Level, Abreeza Mall, JP Laurel Avenue , Davao City','storecode' => '301'),
		array('code' => '1377','nome' => 'Handyman  Capital San Carlos','address' => 'Gound Floor, Gaisano Capital San Carlos, F Ledesma Avenue, Corner Ledesma Street, San Carlos City, Negros Occidental','storecode' => ''),
		array('code' => '1301','nome' => 'AJMS TEST BRANCH 2','address' => 'AJMS TEST BRANCH 2','storecode' => 'AJMS TEST BRANCH 2'),
		array('code' => '1300','nome' => 'AJMS TEST BRANCH 1','address' => 'AJMS TEST BRANCH 1','storecode' => 'AJMS TEST BRANCH 1')
	);
